apiVersion: v1
kind: Service
metadata:
  name: stockvaluator-backend
spec:
  type: ClusterIP
  ports:
    - port: 8500
      targetPort: 8500
  selector:
    app: stockvaluator
    component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: stockvaluator-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3500
      targetPort: 3500
  selector:
    app: stockvaluator
    component: frontend