"""add finviz fair value columns

Revision ID: 04590affdc5b
Revises: 13d46ed760c8
Create Date: 2026-01-29 01:40:11.711825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04590affdc5b'
down_revision: Union[str, Sequence[str], None] = '13d46ed760c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('eps_next_year', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('eps_growth_next_5y', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('dividend_est', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('book_value_per_share', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'book_value_per_share')
    op.drop_column('financial_data', 'dividend_est')
    op.drop_column('financial_data', 'eps_growth_next_5y')
    op.drop_column('financial_data', 'eps_next_year')
    # ### end Alembic commands ###
