"""add net_debt_to_capital_history

Revision ID: 13d46ed760c8
Revises: 53b9c1da5426
Create Date: 2026-01-28 02:58:06.035047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d46ed760c8'
down_revision: Union[str, Sequence[str], None] = '53b9c1da5426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('net_debt_to_capital_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'net_debt_to_capital_history')
    # ### end Alembic commands ###
