"""add financial_data and ai_score_cache tables

Revision ID: 18081f792c5a
Revises: ed1be42da52f
Create Date: 2026-01-25 00:32:42.786955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18081f792c5a'
down_revision: Union[str, Sequence[str], None] = 'ed1be42da52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_score_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('score_type', sa.String(length=50), nullable=False),
    sa.Column('score_value', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_used', sa.String(length=5000), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_score_cache_symbol'), 'ai_score_cache', ['symbol'], unique=False)
    op.create_table('financial_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eps_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revenue_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('net_income_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dividend_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dividend_growth_years', sa.Integer(), nullable=True),
    sa.Column('fcf_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fcf_per_share_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shares_outstanding_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('book_value_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_debt_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cash_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('roe_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('net_margin_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('forward_pe', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('price_to_book', sa.Float(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_data_symbol'), 'financial_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_data_symbol'), table_name='financial_data')
    op.drop_table('financial_data')
    op.drop_index(op.f('ix_ai_score_cache_symbol'), table_name='ai_score_cache')
    op.drop_table('ai_score_cache')
    # ### end Alembic commands ###
