"""add pe_history and dividend_yield_history columns

Revision ID: 53b9c1da5426
Revises: 18081f792c5a
Create Date: 2026-01-28 01:02:05.899657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b9c1da5426'
down_revision: Union[str, Sequence[str], None] = '18081f792c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('pe_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('financial_data', sa.Column('dividend_yield_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'dividend_yield_history')
    op.drop_column('financial_data', 'pe_history')
    # ### end Alembic commands ###
