"""add dividend_growth_5y column

Revision ID: 97cb97f58216
Revises: 04590affdc5b
Create Date: 2026-01-29 21:55:39.027392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97cb97f58216'
down_revision: Union[str, Sequence[str], None] = '04590affdc5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('dividend_growth_5y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_data', 'dividend_growth_5y')
    # ### end Alembic commands ###
