"""Add missing fundamental fields

Revision ID: 984ff034c23c
Revises: 9931b6117256
Create Date: 2026-01-21 01:25:57.199271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984ff034c23c'
down_revision: Union[str, Sequence[str], None] = '9931b6117256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_fundamentals', sa.Column('eps', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('beta', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('fifty_two_week_high', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('stock_fundamentals', sa.Column('fifty_two_week_low', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_fundamentals', 'fifty_two_week_low')
    op.drop_column('stock_fundamentals', 'fifty_two_week_high')
    op.drop_column('stock_fundamentals', 'beta')
    op.drop_column('stock_fundamentals', 'eps')
    # ### end Alembic commands ###
