"""Add notes to trades

Revision ID: 9927ce6d0e21
Revises: cfa489ca90f7
Create Date: 2026-01-14 10:59:05.662295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9927ce6d0e21'
down_revision: Union[str, Sequence[str], None] = 'cfa489ca90f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('notes', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'notes')
    # ### end Alembic commands ###
