"""Add price_alerts and stock_fundamentals tables

Revision ID: 9931b6117256
Revises: ef4f7d93c4f0
Create Date: 2026-01-19 21:21:34.526309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9931b6117256'
down_revision: Union[str, Sequence[str], None] = 'ef4f7d93c4f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_fundamentals',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('major_shareholders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_fundamentals_symbol'), 'stock_fundamentals', ['symbol'], unique=True)
    op.create_table('price_alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'INACTIVE', name='alertstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_status'), 'price_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_price_alerts_symbol'), 'price_alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_alerts_user_id'), 'price_alerts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alerts_user_id'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_symbol'), table_name='price_alerts')
    op.drop_index(op.f('ix_price_alerts_status'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index(op.f('ix_stock_fundamentals_symbol'), table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    # ### end Alembic commands ###
