"""Add notes to cash transactions

Revision ID: ef4f7d93c4f0
Revises: 9927ce6d0e21
Create Date: 2026-01-15 00:43:44.404855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef4f7d93c4f0'
down_revision: Union[str, Sequence[str], None] = '9927ce6d0e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_transactions', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cash_transactions', 'notes')
    # ### end Alembic commands ###
